"""empty message

Revision ID: 4cea10f5c531
Revises: 4e339baa9995
Create Date: 2020-12-24 15:55:10.439620

"""

# revision identifiers, used by Alembic.
revision = "4cea10f5c531"
down_revision = "4e339baa9995"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
