"""empty message

Revision ID: 4e339baa9995
Revises: 18d47e8f0ca4
Create Date: 2020-12-17 18:54:54.153921

"""

# revision identifiers, used by Alembic.
revision = "4e339baa9995"
down_revision = "18d47e8f0ca4"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
